export const DANCE_STYLES = [
    "Ballet",
    "Hip Hop",
    "Salsa",
    "Bachata",
    "Contemporary",
    "Jazz",
    "Tap Dance",
    "Tango",
    "Ballroom",
    "Swing",
    "Modern Dance",
    "Street Dance",
    "Breakdancing",
    "K-Pop",
    "Zumba",
    "Belly Dance",
    "Bollywood",
    "Afrobeats",
    "Reggaeton",
    "Commercial",
    "House",
    "Heels",
    "Musical Theatre",
    "Lyrical",
    "Kizomba",
    "Urban Kiz",
    "Semba",
    "Tarraxinha",
    "Kizomba Fusion",
    "Waacking",
    "Vogue",
    "Capoeira",
    "Flamenco",
    "Samba",
    "Folk Dance",
    "Pole Dance",
    "Aerial Arts"
].sort();
